---
title: "Parking Violations"
output: html_notebook
---

A review of parking citation data in Baltimore
https://data.baltimorecity.gov/datasets/baltimore::parking-and-moving-citations/explore?showTable=true

```{r}

# Turn off scientific notation
options(scipen=999)
# Load the tidyverse,janitor
library(tidyverse)
library(janitor)
#install.packages("jsonlite")
library(jsonlite)

```

```{r}

# Path to the JSON file
#json_file <- "https://services1.arcgis.com/UWYHeuuJISiGmgXx/arcgis/rest/services/Finance_Parking_Fines/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json"

json_file <- "https://services1.arcgis.com/UWYHeuuJISiGmgXx/arcgis/rest/services/Finance_Parking_Fines/FeatureServer/0/query?where=0%3D0&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token="

# Import JSON data into R
json_data <- fromJSON(json_file)

parking_tix1 <-json_data[["features"]][["attributes"]]

parking_tix <- parking_tix1 %>%  
  clean_names() %>% 
  mutate(timestamp_seconds = viol_date / 1000) %>% 
  mutate(datetime = as.POSIXct(timestamp_seconds, origin = "1970-01-01", tz = "UTC")) %>% 
  mutate(year = year(datetime))


# parking_tix$year <- sub("^([0-9]{4}).*", "\\1", parking_tix$viol_date)
# 
# parking_2022_2023 <- parking_tix %>% 
#   filter(year > 2021) 
# 
# write.csv(parking_2022_2023, "parking_2022_2023.csv")
# write_rds(parking_2022_2023, "parking_2022_2023.rds")


parking_tix %>% 
  group_by(year) %>% 
  count()

```

# fix makes
```{r}

parking_tix <- parking_tix %>% 
  mutate(make_clean = make) %>% 
  mutate(make_clean = case_when(
    make_clean =="HOND" ~ "HONDA",
    make_clean =="YAMAH" ~ "YAMAHA",
    TRUE ~ make_clean))
  
makes <- parking_tix %>% 
  group_by(make_clean) %>% 
  count() %>% 
  filter(n > 100) %>% 
  arrange(desc(make_clean))

```
