---
title: "foot traffic maps"
author: "Rob Wells and Rachel Logan"
date: "2/21/2025"
output: html_document
---

```{r message=FALSE, warning=FALSE}
#remotes::install_github("walkerke/tidycensus")
library(tidyverse)
library(tidycensus)
#a = get_decennial(geography = "state", variables = "P1_001N", year = 2020)
# head(a, 5)
#install.packages("formattable")
library(formattable)
library(htmlwidgets)
#install.packages("leaflet")
library(leaflet)
library(sf)
library(formattable)
library(janitor)
#install.packages("leaflet.extras")
library(leaflet.extras)
library(googlesheets4)

```

Census API key.

```{r message=FALSE}
census_api_key("9cabe8a191a1f824755d4a1845f13cb08faa2c5f", install = TRUE, overwrite = TRUE)
```

# --------------------------------------
# Maryland Data Import:  Smith School 
# --------------------------------------

```{r}
md <- rio::import("../data/maryland_tracts.xls") %>% 
  as.data.frame()

md <- md %>% 
  clean_names() %>% 
  mutate(census = as.character(tract)) %>% 
  mutate(county = as.numeric(strtrim(tract, 5))) %>% 
  mutate(geoid = as.numeric(strtrim(tract, 7))) %>% 
  mutate(geoid1 = as.character((geoid))) %>% 
  mutate(zip1 = as.character((zip)))
```


```{r}
mdzip <- rio::import("../data/ZIP_TRACT_122023.xlsx")



md_places <- md %>% 
  inner_join(mdzip, by=c("zip1"="ZIP")) %>% 
  distinct(tract, .keep_all = TRUE) %>% 
  mutate(pct_anymembershp1 = formattable::percent(pct_anymembershp_zip)) |> 
  janitor::clean_names() 


#write.csv(md_places, "../data/smith_md_places_april1.csv")
```

# Simply Smith Data for B'more class
```{r}
md_places_brief <- md_places |> 
   select(usps_zip_pref_city,  income_per_capita, census_response_rate2020, census_response_rate2010, nbanks_zip, pct_anymembershp_zip, zip, tot_pop, age_above65, median_age, white, black, asian, geoid1, tract) |> 
  rename(city = usps_zip_pref_city)

#write.csv(md_places_brief, "smith_school_brief_version_1_27-2025.csv")

md_places_full <- md_places |> 
     select(usps_zip_pref_city,  income_per_capita, census_response_rate2020, census_response_rate2010, nbanks_zip, pct_anymembershp_zip, zip, tot_pop, age_above65, median_age, white, black, asian, edu_highschool, edu_bachelor,edu_graduate, income_0to10k, income_10to50k, income_50to100k, income_100to200k, income_200k, income_median, income_per_capita, occupation_management, occupation_sales, occupation_naturalresource, occupation_production, res_ratio, bus_ratio, oth_ratio,tot_ratio,pct_anymembershp1,geoid1, tract, census) |> 
  rename(city = usps_zip_pref_city)

#write.csv(md_places_full, "smith_school_w_places_full_version_1_27-2025.csv")

```

# Import Foot Traffic Data
```{r}
#list of businesses losing foot traffic y-y
dundalk <- read.csv("../data/dundalk_loser.csv")
arundel <- read.csv("../data/arundel_loser.csv")

foot_geo <- read.csv("../data/foot_traffic_geocode_lookup.csv")
```

# Geocode dundalk
```{r}



dundalk1 <- dundalk |> 
  inner_join(foot_geo, by=c("location_name", "street_address", "city", "region", "postal_code")) |> 
select(
  "location_name", "street_address", "city", "region", "postal_code",
  "foot_traffic_yoy", "address", "placekey", "naics4", "poi_tract",
  "nvisits", "nvisits_lyear", "nvisitor_total", "dln_visits_yoy.y",
  "pct_nvisitor_same_cty", "pct_nvisitor_same_tract", "pct_nvisitor_within_1mile",
  "pct_nvisitor_within_5mile", "pct_nvisitor_within_10mile", "pct_nvisitor_outside_10mile",
  "brands", "max_nvisits", "min_nvisits", "fulladdress", "lon", "lat"
) |> 
  rename(dln_visits_yoy = dln_visits_yoy.y)
library(sf)

dundalk1 <- st_as_sf(dundalk1, coords = c("lon", "lat"), crs = 4326)

# md_named <- st_set_crs(md_named, 4326) %>%
#   st_transform(4326)
# 
# md_named <- md_named %>%
#   st_as_sf(., coords = c("lon", "lat")) %>%
#   st_buffer(dist = 0.01) # convert points to polygons

```





```{r}
# Create color palette for the points
pal <- colorNumeric(
  palette = "inferno",
  domain = dundalk1$dln_visits_yoy 
)

# Create the leaflet map
leafMap <- leaflet() %>%
  # Add base map
  addProviderTiles(providers$Esri.WorldStreetMap) %>%
  # Set view to Dundalk's approximate coordinates and zoom level
  setView(lng = -76.52, lat = 39.27, zoom = 13) %>%
  # Add points for businesses
  addCircleMarkers(
    data = dundalk1,
    radius = 8,
    color = "black",
    weight = 1,
    fillColor = ~pal(dln_visits_yoy),
    fillOpacity = 0.7,
    popup = ~paste("<b>", location_name, "</b><br>",
                  "Change in foot traffic: ", round(dln_visits_yoy, 2), "%<br>",
                  "Address: ", fulladdress)
  ) %>%
  # Add legend
  addLegend(
    position = "bottomright",
    pal = pal,
    values = dundalk1$dln_visits_yoy,
    title = "Change in Foot Traffic",
    labFormat = labelFormat(transform = function(x) round(x, 2))
  ) %>%
  # Add title
  addControl(
    html = "<div style='background-color: white; padding: 5px; border-radius: 3px;'><h3>Decline in Foot Traffic at Dundalk Businesses since Key Bridge Collapse</h3></div>",
    position = "topright"
  )
saveWidget(leafMap, "../output/foot_traffic_decline_map_feb_2025.html")
leafMap
```



```{r}
dundalk |> 
  count(location_name) |> 
  arrange(desc(n))

```



#Map by county
```{r}
md_named <- read.csv("../output/md_smith_data_12.16.csv") %>% 
  rename(lat = INTPTLAT, long = INTPTLONG)


library(sf)

md_named <- st_as_sf(md_named, coords = c("long", "lat"), crs = 4326)

md_named <- st_set_crs(md_named, 4326) %>%
  st_transform(4326)

md_named <- md_named %>%
  st_as_sf(., coords = c("long", "lat")) %>%
  st_buffer(dist = 0.01) # convert points to polygons

#addCircles(data = md_named, radius = 500, fillOpacity = 0.5, ...)
# #Map by Median Income Difference
# md_named<- md_named %>% 
#    sf::st_transform('+proj=longlat +datum=WGS84')
```



# Census Tract Median Income Using ACS

#Subset geocoordinates
```{r}
#subset the geometry

#2020 Median Income By Census Tract ACS
#2016-2020
#B19001 COUNTS THE NUMBER OF HOUSEHOLDS
#B19013_001 is the household median income
md_income2020_geo <- get_acs(geography = "tract", 
              variables = c(number_households = "B19001_001", median_income = "B19013_001"), 
               state = "MD", 
               year = 2020, geometry = TRUE) %>% 
  mutate(year=("2020")) %>% 
  select(GEOID, NAME)

maryland_places_data <- get_acs(geography = "place",
                                 variables = c(number_households = "B19001_001", median_income = "B19013_001"),
                                 state = "MD",
                                 year = 2020)


# Retrieve ACS data for places in Maryland
places_data <- get_acs(geography = "place",
                        variables = c(number_households = "B19001_001", median_income = "B19013_001"),
                        state = "MD",
                        year = 2020)

# Retrieve ACS data for tracts in Maryland
# Ensure caching of shapefiles
options(tigris_use_cache = TRUE)
tracts_data <- get_acs(geography = "tract",
                        variables = c(number_households = "B19001_001", median_income = "B19013_001"),
                        state = "MD",
                        year = 2020,
                        geometry = TRUE)

# Merge the place and tract data
maryland_data <- bind_rows(places_data, tracts_data)

#B19013 defined: https://www.socialexplorer.com/data/ACS2010_5yr/metadata/?ds=ACS10_5yr&var=B19013001

md_named <- md_named %>% 
  mutate(GEOID = as.character(tract))

#FIX
# Convert sf object to regular data frame
md_income2020_regular <- st_drop_geometry(md_income2020_geo)

# Then do the regular join
md2 <- md_income2020_regular %>%
  right_join(md_named, by = "GEOID") %>%
  distinct()


#join geocoordinates 
# md2 <- md_income2020_geo  %>% 
#  right_join(md_named, by=c("GEOID")) %>% 
#  distinct()

md2 <- st_as_sf(md2)

md2 <- md2 %>%
   sf::st_transform('+proj=longlat +datum=WGS84')


```





```{r}
pal <- colorNumeric(
  palette = "inferno",
  domain = md2$pct_anymembershp_zip
)

#https://leaflet-extras.github.io/leaflet-providers/preview/
leafMap <- leaflet() %>%
  addProviderTiles(providers$Esri.WorldStreetMap) %>%
  addPolygons(data = md2,
              color = ~pal(md2$pct_anymembershp_zip),
              weight = 2.5,
              smoothFactor = 0.2,
              fillOpacity = 0.5,
  label = paste("Pct membership in civic groups is:",(md2$pct_anymembershp_zip), "Income is",(md2$income_per_capita), "in", (md2$NAME.y), "zip code", (md2$zip))) %>%
 addControl(
    html = '<div id="legend" style="background-color: white; padding: 10px; border-radius: 5px; border: 1px solid #ccc; text-align: center;">
              <p><strong>Pct Membership 2020</strong></p>
              <div style="background-color: gray; height: 20px; width: 30px; display: inline-block;"></div> 0: NA
              <br>
              <div style="background-color: black; height: 20px; width: 30px; display: inline-block;"></div> 30-39%
              <br>
              <div style="background-color: #e75480; height: 20px; width: 30px; display: inline-block;"></div> 40-45%
              <br>
              <div style="background-color: #fa8072; height: 20px; width: 30px; display: inline-block;"></div> 46-50%
              <br>
              <div style="background-color: #ffffbf; height: 20px; width: 30px; display: inline-block;"></div> 51-60%
           </div>',
    position = "bottomright"
  ) %>% 
  addControl(
    html = "<div style='background-color: white; padding: 5px; border-radius: 3px;'><h3>Civil Membership & Income in Maryland</h3></div>",
    position = "topright"
  )

#saveWidget(leafMap, "../output/state_member_all_map_jan_28.html")
leafMap
```
