---
title: "Water_Main_Breaks"
author: "Wells"
date: "2025-04-14"
output: html_document
---
```{r}
library(tidyverse)
library(tidyr)
library(ggmap)
#register_google(key = "XXXX")
```

import data
```{r}
water <- read.csv("../data/tabula-2024-2025 Water Main Breaks.csv")

# First, create a new data frame with the original column names as the first row
first_row <- data.frame(
  col1 = colnames(water)[1],
  col2 = colnames(water)[2],
  col3 = colnames(water)[3],
  col4 = colnames(water)[4],
  stringsAsFactors = FALSE
)

# Now rename the columns in both data frames with your desired names
colnames(first_row) <- c("workorderid", "date", "description", "address")
colnames(water) <- c("workorderid", "date", "description", "address")

# Combine the data frames
water_complete <- rbind(first_row, water)

water_complete[1, "workorderid"] <- "1286160"
water_complete[1, "date"] <- "1/2/2024"
water_complete[1, "description"] <- "WATER MAIN BREAK"
water_complete[1, "address"] <- "5614 WINTHROPE AVE"


water <- water_complete
```


#prepare data
```{r}

water <- water |> 
  mutate(address1 = paste0(address, ", ", "baltimore"))

```

```{r}
water <- water %>%
  mutate(details = ifelse(grepl("^[0-9]", address), "yes", "no")) |> 
  mutate(date1 = as.Date(date, "%m/%d/%Y" )) |> 
  mutate(yearmo = zoo::as.yearmon(date1, "%m_%Y")) +
  


```

```{r}
water |> 
  count(yearmo) |> 
  mutate(pct = round(n/sum(n),2)) |> 
  arrange(yearmo) |> 
   ggplot(aes(x = yearmo, y = n, fill = n)) +
  geom_col(position = "dodge", show.legend = FALSE) +
  labs(title = "Water Main Breaks, Leaks in Baltimore Area, 2024 - Feb 2025",
       subtitle = "Primarily water main breaks",
       caption = "Graphic by Rob Wells, 4-14-2025",
       y="Number of Breaks",
       x="Year-Month") +
    scale_x_continuous(breaks = as.numeric(unique(water$yearmo)),
                     labels = format(unique(water$yearmo), "%b %Y")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))




```




# full address vs intersections   
```{r}

water |> 
  count(details)

#9.4% of the addresses lack numbers and are intersections


water |> 
  count(address) |> 
  filter(n > 1) |> 
  arrange(desc(n))
```

#filtered to just addresses
```{r}

filtered_water <- water |> 
  filter(details == "yes")

write.csv(filtered_water, "../data/filtered_water.csv")

```

#Potholes
```{r}
library(zoo)
pothole2024 <- read.csv("../data/311_Customer_Service_Requests_2024.csv") |> 
  mutate(created_date_new = mdy_hms(CreatedDate)) |> 
  mutate(yearmo = floor_date(created_date_new, "month")) |> 
  mutate(year = year(created_date_new))

pothole2025 <- read.csv("../data/311_Customer_Service_Requests_2025_-1251820653633891040.csv") |> 
  filter(SRType == c("TRM-Pickup Pothole", "TRM-Potholes")) |> 
  mutate(ESRI_OID = "_") |> 
  mutate(created_date_new = mdy_hm(CreatedDate)) |> 
  mutate(yearmo = floor_date(created_date_new, "month")) |> 
  mutate(year = year(created_date_new))

potholes <- rbind(pothole2024, pothole2025)

# library(lubridate)
# potholes <- potholes |> 
#   mutate(created_date_new = mdy_hms(CreatedDate)) |> 
#   mutate(yearmo = floor_date(created_date_new, "month")) |> 
#   mutate(year = year(created_date_new))

write.csv(potholes, "all_potholes.csv")
```


# Potholes by neighborhoood and yearmo

```{r}
sum_pothole_wide <- potholes |> 
  filter(yearmo == as.Date("2025-03-01") | yearmo == as.Date("2024-03-01")) |> 
  group_by(Neighborhood, year) |>
  summarize(count = n(), .groups = "drop") |>
  # Reshape data to have separate columns for 2024 and 2025
  pivot_wider(
    names_from = year,
    values_from = count,
    values_fill = 0  # Fill with 0 if no data for that year
  )

write.csv(sum_pothole_wide, "march_pothole_totals.csv")
```





#GEOCODE
```{r}

losers <- losers %>% 
  mutate(geo = geocode(address)) 

losers <- losers %>%
  tidyr::unnest(geo)


losers <- st_as_sf(losers, coords = c("lon", "lat"), crs = 4326)

# write.csv(losers, "dundalk_arundel_losers.csv")

```

