---
title: "Unemployment Data Analysis"
author: Matt Cohen
---

```{r}
library(DatawRappr)
library(tidyverse)
datawrapper_auth(api_key =  "Fill in API key here", overwrite=TRUE)
library(janitor)
library(lubridate)
library(htmltools)

```

**Loading original data set**

```{r}
ui_data <- read_csv("ui_data.csv") |> clean_names() 
```

```{r}
ui_data$zip <- as.character(ui_data$zip)
ui_data$month <- as.character(ui_data$month)
```

**Adding location data**

```{r}
locations <- read_csv("https://raw.githubusercontent.com/profrobwells/Baltimore/refs/heads/main/fall_2024_indep_study/data/county_zip.csv") |> clean_names() 
```

```{r}
locations$zip <- as.character(locations$zip)
```

**Joining data and creating pivot table to group by zip code**

```{r}
combined_data <- left_join(ui_data, locations, by="zip")
```

```{r}
ui_pivot <- combined_data |>
  group_by(zip, primary_city) |>
  summarize(count = sum(count)) |>
  arrange(desc(count)) 
```

**Beginning map creation**

```{r}
map <- dw_create_chart(type = "d3-maps-choropleth", title = "Unemployment stats"
)
 
```

```{r}
dw_data_to_chart(ui_pivot, chart_id = map)
```

```{r}
view(dw_basemaps)
```

```{r}
dw_edit_chart(map, 
              axes = list(
                values = "count"
                ), 
              visualize = list(
                basemap = "maryland-postcode"
                )
              )
```

```{r}
dw_publish_chart(map)
```

```{r}
iframe_code <- '<iframe src="https://datawrapper.dwcdn.net/Jhbsf/1/" width="100%" height="400" style="border: none;"></iframe>'
HTML(iframe_code)
```

**Adding weekly county-level UI data**

```{r}
counties_ui_raw <- read_csv("filtered_ui_counties.csv") |> clean_names()
```

```{r}
counties_ui_raw <- counties_ui_raw 
```

**Creating county level chart**

```{r}
weekly_ui_line <- dw_create_chart()
```

```{r}
dw_data_to_chart(counties_ui_raw, weekly_ui_line)
```

```{r}
dw_edit_chart(weekly_ui_line, title = "Weekly unemployment insurnace claims spiked in surrounding counties after Key Bridge collapse", intro = "The week ending March 30 had the most amounts of unemployment insurance claims of any week in 2024 in Maryland. The Key Bridge collapsed on March 26", byline = "Matt Cohen", source_name = "Maryland Dept. of Labor")


```

```{r}
dw_publish_chart(weekly_ui_line)
```
```{r}
iframe_code <- '<iframe src="https://datawrapper.dwcdn.net/YGqTg/1/" width="100%" height="400" style="border: none;"></iframe>'
HTML(iframe_code)
```

